nc = input('Digite seu nome completo: ')
mai = nc.upper()
min = nc.lower()
carac = (nc.split())
tcarac = len(''.join(carac))
prim = len(nc.split()[0])
print('Seu nome em letras maíusculas é {}.'.format(mai))
print('Seu nome em letras minúsculas é {}.'.format(min))
print('Seu nome possui {} caracteres.'.format(tcarac))
print('Seu primeiro nome possui {} caracteres.'.format(prim))
